### ISSUE TITLE
All Unit Tests Fail in Unix

### ISSUE THREAD

**Issue by swbrenneis** [LoboEvolution/LoboEvolution#67]
None of the unit tests pass. One problem was that they were all in the wrong package. They still fail after correcting that problem.

**Comment by JasonTheKitten** [comment]
At least the unit tests exist (I can't say that of my own projects)
When you are working on a project of this scale and you are about the only person working on it, it can be hard to maintain everything.

**Comment by oswetto** [comment]
Hello @swbrenneis i've download code in my folder "C:\Users\user\Desktop\Code\LoboEvolution" and execute command "mvn clean compile surefire-report:report", code compile without errors and all unit tests are executed and my result is "Tests run: 1552, Failures: 620, Errors: 0, Skipped: 0"

**Comment by oswetto** [comment]
@swbrenneis ps i'm very interessed a your embedded version

**Comment by swbrenneis** [comment]
I will definitely keep you up to date. Where is the best place to contact you?

**Comment by oswetto** [comment]
@swbrenneis you can write in discussion section

**Comment by DaveJarvis** [comment]
There are a few problems with the tests.

* All occurrences of `"\\"` must be replaced with `File.pathSeparator`.
* The tests require `LOBOEVOLUTION_STORAGE.sqlite` under the user's home directory.

The first issue is simple. The second issue violates the [XDG specifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and would be better located using a directory relative to the unit tests (i.e., a `resources` directory).

A third issue is that a database is being used. For folks who are looking for an HTML + CSS rendering component for Java, a database is not needed. Ideally, it would be in a separate module or project so that it can be brought in independently.

**Comment by oswetto** [comment]
@swbrenneis fixed. Thanks @DaveJarvis for your suggestion
